templates: add sticky footer
cernopendata/cernopendata pull request #30
Opened 2017-08-18 15:43 UTC by hjhsalo

* Fix footer scaling issues by introducing a sticky footer
  (closes cernopendata/cernopendata-pages#9)

* Fix footer stacking issues on smaller screens

Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>

2017-08-21 08:29 UTC, ioannistsanaktsidis commented
Works pretty good, just needs a bit of refactoring in terms of moving scss to a  separate file.

2017-08-22 07:52 UTC, tiborsimko commented
@hjhsalo @ioannistsanaktsidis Is this mergable now? It would be good to get all the pending PRs in before we freeze the repositories for the code move.

2017-08-22 07:56 UTC, hjhsalo commented
Mergeable, but waiting for review / comments on refactoring:
* SCSS refactored to its own file now.
* Visually OK.
* Rebased on top of current next-branch.

2017-08-22 08:16 UTC, ioannistsanaktsidis requested changes
It looks good to me, only one small change and then we can merge it.

2017-08-22 08:16 UTC, ioannistsanaktsidis commented on cernopendata/modules/theme/static/scss/footer.scss
> +html, body {
I think this one can be moved to the general styles.scss

2017-08-22 12:13 UTC, hjhsalo commented on cernopendata/modules/theme/static/scss/footer.scss
> +html, body {
Changed

2017-08-22 14:41 UTC, ioannistsanaktsidis approved these changes

2017-08-22 14:50 UTC, merged